#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
PUMA_CONF="$DIR/config/puma.rb"

start_daemon() {
  RAILS_ENV=production bundle exec puma -C "$PUMA_CONF"
}

stop_daemon() {
  pumactl -S "$DIR/log/puma.state" stop
}

restart_daemon() {
  pumactl -S "$DIR/log/puma.state" restart
}

case $1 in
  start)
    start_daemon
  ;;
  stop)
    stop_daemon
  ;;
  restart)
    restart_daemon
  ;;
  *)
    echo "usage: $0 start|stop|restart"
    exit 1
  ;;
esac
